<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\YbsSmartCardSystem.Database\YbsSmartCardSystem.Database.csproj" />
    <ProjectReference Include="..\YbsSmartCardSystem.Contracts\YbsSmartCardSystem.Contracts.csproj" />
    <ProjectReference Include="..\YbsSmartCardSystem.Shared\YbsSmartCardSystem.Shared.csproj" />
    <ProjectReference Include="..\YbsSmartCardSystem.Infrastructure\YbsSmartCardSystem.Infrastructure.csproj" />
  </ItemGroup>

</Project>
