// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YbsSmartCardSystem.Database.AppDbContextModels;

#nullable disable

namespace YbsSmartCardSystem.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809061155_AddCreatedByFields")]
    partial class AddCreatedByFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblAuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AuditLogId");

                    b.HasIndex(new[] { "Action" }, "IX_Tbl_AuditLog_Action");

                    b.HasIndex(new[] { "CreatedDateTime" }, "IX_Tbl_AuditLog_CreatedDateTime");

                    b.HasIndex(new[] { "FeatureName" }, "IX_Tbl_AuditLog_FeatureName");

                    b.HasIndex(new[] { "UserId" }, "IX_Tbl_AuditLog_UserId");

                    b.ToTable("Tbl_AuditLog", (string)null);
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblBu", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusId"));

                    b.Property<string>("BusLicense")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BusNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.HasKey("BusId")
                        .HasName("PK__Tbl_Bus__6A0F60B5CD2F452C");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "BusNo" }, "UQ__Tbl_Bus__6A0F3A401D8FBE4D")
                        .IsUnique();

                    b.ToTable("Tbl_Bus", (string)null);
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblCard", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CardNum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CardId")
                        .HasName("PK__Tbl_Card__55FECDAE92BF02E6");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "CardNum" }, "IX_Tbl_Card_CardNum")
                        .IsUnique();

                    b.HasIndex(new[] { "CardNum" }, "UQ__Tbl_Card__9B6B7CD1DA8BE5F0")
                        .IsUnique();

                    b.HasIndex(new[] { "MobileNo" }, "UX_Tbl_Card_MobileNo_Active")
                        .IsUnique()
                        .HasFilter("([DeleteFlag]=(0) AND [MobileNo] IS NOT NULL)");

                    b.ToTable("Tbl_Card", (string)null);
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblCardRegistrationOtp", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<int>("MaxAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("OtpCodeHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime");

                    b.HasKey("OtpId")
                        .HasName("PK__Tbl_Card__3143C4A337CE20E7");

                    b.HasIndex(new[] { "CreatedByUserId" }, "IX_Tbl_CardRegistrationOtp_CreatedByUserId");

                    b.HasIndex(new[] { "ExpiresAt" }, "IX_Tbl_CardRegistrationOtp_ExpiresAt");

                    b.HasIndex(new[] { "PhoneNumber" }, "IX_Tbl_CardRegistrationOtp_PhoneNumber");

                    b.ToTable("Tbl_CardRegistrationOtp", (string)null);
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblPermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("PermissionId");

                    b.HasIndex(new[] { "FeatureName" }, "IX_Tbl_Permission_FeatureName");

                    b.HasIndex(new[] { "IsActive" }, "IX_Tbl_Permission_IsActive");

                    b.HasIndex(new[] { "PermissionCode" }, "UX_Tbl_Permission_PermissionCode_Active")
                        .IsUnique()
                        .HasFilter("([DeleteFlag]=(0))");

                    b.ToTable("Tbl_Permission", (string)null);
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("RoleId");

                    b.HasIndex(new[] { "RoleCode" }, "UX_Tbl_Role_RoleCode_Active")
                        .IsUnique()
                        .HasFilter("([DeleteFlag]=(0))");

                    b.ToTable("Tbl_Role", (string)null);
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblRolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePermissionId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RolePermissionId");

                    b.HasIndex(new[] { "PermissionId" }, "IX_Tbl_RolePermission_PermissionId");

                    b.HasIndex(new[] { "RoleId" }, "IX_Tbl_RolePermission_RoleId");

                    b.HasIndex(new[] { "RoleId", "PermissionId" }, "UX_Tbl_RolePermission_Role_Permission_Active")
                        .IsUnique()
                        .HasFilter("([DeleteFlag]=(0))");

                    b.ToTable("Tbl_RolePermission", (string)null);
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblStaffUser", b =>
                {
                    b.Property<int>("StaffUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffUserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StaffUserId");

                    b.HasIndex(new[] { "UserName" }, "UX_Tbl_StaffUser_UserName_Active")
                        .IsUnique()
                        .HasFilter("([DeleteFlag]=(0))");

                    b.ToTable("Tbl_StaffUser", (string)null);
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblTerminal", b =>
                {
                    b.Property<int>("TerminalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TerminalId"));

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TerminalSerialNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TerminalId")
                        .HasName("PK__Tbl_Term__6A7262A9048CE6EA");

                    b.HasIndex("BusId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "TerminalSerialNo" }, "UQ__Tbl_Term__8B909E83BAEF313A")
                        .IsUnique();

                    b.ToTable("Tbl_Terminal", (string)null);
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblTopUp", b =>
                {
                    b.Property<int>("TopUpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopUpId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("Remark")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("TopUpDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("TopUpNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.HasKey("TopUpId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "CardId" }, "IX_Tbl_TopUp_CardId");

                    b.HasIndex(new[] { "TopUpDate" }, "IX_Tbl_TopUp_TopUpDate");

                    b.HasIndex(new[] { "TopUpNo" }, "IX_Tbl_TopUp_TopUpNo")
                        .IsUnique();

                    b.ToTable("Tbl_TopUp", (string)null);
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<int>("TerminalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("TransactionNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.HasKey("TransactionId")
                        .HasName("PK__Tbl_Tran__55433A6BC2287FDE");

                    b.HasIndex("CardId");

                    b.HasIndex("TerminalId");

                    b.ToTable("Tbl_Transaction", (string)null);
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblUserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_Tbl_UserRole_RoleId");

                    b.HasIndex(new[] { "UserId" }, "IX_Tbl_UserRole_UserId");

                    b.HasIndex(new[] { "UserId", "RoleId" }, "UX_Tbl_UserRole_User_Role_Active")
                        .IsUnique()
                        .HasFilter("([DeleteFlag]=(0))");

                    b.ToTable("Tbl_UserRole", (string)null);
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblViewerUser", b =>
                {
                    b.Property<int>("ViewerUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViewerUserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ViewerUserId");

                    b.HasIndex(new[] { "PhoneNo" }, "UX_Tbl_ViewerUser_PhoneNo_Active")
                        .IsUnique()
                        .HasFilter("([DeleteFlag]=(0))");

                    b.HasIndex(new[] { "UserName" }, "UX_Tbl_ViewerUser_UserName_Active")
                        .IsUnique()
                        .HasFilter("([DeleteFlag]=(0))");

                    b.ToTable("Tbl_ViewerUser", (string)null);
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblBu", b =>
                {
                    b.HasOne("YbsSmartCardSystem.Database.AppDbContextModels.TblStaffUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_TblBus_TblStaffUser");

                    b.Navigation("CreatedUser");
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblCard", b =>
                {
                    b.HasOne("YbsSmartCardSystem.Database.AppDbContextModels.TblStaffUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_TblCard_TblStaffUser");

                    b.Navigation("CreatedUser");
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblRolePermission", b =>
                {
                    b.HasOne("YbsSmartCardSystem.Database.AppDbContextModels.TblPermission", "Permission")
                        .WithMany("TblRolePermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("FK_Tbl_RolePermission_Tbl_Permission");

                    b.HasOne("YbsSmartCardSystem.Database.AppDbContextModels.TblRole", "Role")
                        .WithMany("TblRolePermissions")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Tbl_RolePermission_Tbl_Role");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblTerminal", b =>
                {
                    b.HasOne("YbsSmartCardSystem.Database.AppDbContextModels.TblBu", "Bus")
                        .WithMany("TblTerminals")
                        .HasForeignKey("BusId")
                        .IsRequired()
                        .HasConstraintName("FK_Terminal_Bus");

                    b.HasOne("YbsSmartCardSystem.Database.AppDbContextModels.TblStaffUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_TblTerminal_TblStaffUser");

                    b.Navigation("Bus");

                    b.Navigation("CreatedUser");
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblTopUp", b =>
                {
                    b.HasOne("YbsSmartCardSystem.Database.AppDbContextModels.TblCard", "Card")
                        .WithMany("TblTopUps")
                        .HasForeignKey("CardId")
                        .IsRequired()
                        .HasConstraintName("FK_TopUp_Card");

                    b.HasOne("YbsSmartCardSystem.Database.AppDbContextModels.TblStaffUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_TblTopUp_TblStaffUser");

                    b.Navigation("Card");

                    b.Navigation("CreatedUser");
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblTransaction", b =>
                {
                    b.HasOne("YbsSmartCardSystem.Database.AppDbContextModels.TblCard", "Card")
                        .WithMany("TblTransactions")
                        .HasForeignKey("CardId")
                        .IsRequired()
                        .HasConstraintName("FK_Transaction_Card");

                    b.HasOne("YbsSmartCardSystem.Database.AppDbContextModels.TblTerminal", "Terminal")
                        .WithMany("TblTransactions")
                        .HasForeignKey("TerminalId")
                        .IsRequired()
                        .HasConstraintName("FK_Transaction_Terminal");

                    b.Navigation("Card");

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblUserRole", b =>
                {
                    b.HasOne("YbsSmartCardSystem.Database.AppDbContextModels.TblRole", "Role")
                        .WithMany("TblUserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Tbl_UserRole_Tbl_Role");

                    b.HasOne("YbsSmartCardSystem.Database.AppDbContextModels.TblStaffUser", "User")
                        .WithMany("TblUserRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Tbl_UserRole_Tbl_StaffUser");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblBu", b =>
                {
                    b.Navigation("TblTerminals");
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblCard", b =>
                {
                    b.Navigation("TblTopUps");

                    b.Navigation("TblTransactions");
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblPermission", b =>
                {
                    b.Navigation("TblRolePermissions");
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblRole", b =>
                {
                    b.Navigation("TblRolePermissions");

                    b.Navigation("TblUserRoles");
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblStaffUser", b =>
                {
                    b.Navigation("TblUserRoles");
                });

            modelBuilder.Entity("YbsSmartCardSystem.Database.AppDbContextModels.TblTerminal", b =>
                {
                    b.Navigation("TblTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
